server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GabiLenz/Trabalho-Final-Java
          search-paths:
          - microservices-java/configs/{application}
          #username: GabiLenz
          #password: senha
